### ISSUE TITLE
Add more documentations

### ISSUE THREAD

**Issue by Bujupah** [Bujupah/yet-another-renderer#14]
**Todo docs enhancements:**
- [ ] Add apis to docs
- [ ] Add panel png rendering to docs
- [ ] Add multi panel png rendering to docs
- [ ] Add dashboard png rendering to docs
- [ ] Add panel pdf rendering to docs
- [ ] Add multi panel pdf rendering to docs
- [ ] Add dashboard pdf rendering to docs
- [ ] Add pdf cover to docs
- [ ] Add env variables & configuration docs
